services:
  postgres:
    image: postgres:16-alpine
    container_name: storeproject-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: store
      POSTGRES_PASSWORD: storepass_dev
      POSTGRES_DB: storedb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U store -d storedb"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata:
